Disable ceph-pools-audit chart by default
Since most customers do not need this audit, the chart will be
disabled by default, which will prevent an unnecessary periodic
CrobnJob from being triggered. But the customer's can choose to
enable the audit via the 'system helm-chart-attribute-modify'
if desired.

system helm-override-list platform-integ-apps -l

system helm-chart-attribute-modify --enabled true \
platform-integ-appsceph-pools-audit kube-system

system helm-chart-attribute-modify --enabled false \
platform-integ-apps ceph-pools-audit kube-system

system application-apply platform-integ-apps

Additionally, the cephfs and rbd storage-init scripts have been
changed to set the 'min_size' of their respective pools.

Finally, the ceph-pools-audit chart was a CronJob and was replaced
by a Deployment to avoid processing spikes every time the job was
executed. And also the audit script was optimized to execute the
minimum number of ceph commands.

NOTE: This chart will be disabled for new upload/applies only
(i.e. initial installs). If already have a version applied, it
will use whatever is set in the 'system helm-override-list'
command.

PS: The patch 0017 has been removed and the change has
been made directly in the patch 0008, as ​​it is a new
file (template) created by us, not upstream.

Test Plan:
 PASS: On a fresh install, apply the app and check if
       the chart is disabled
 PASS: Check the chart status with
       'system helm-override-list platform-integ-apps -l',
       update the app and confirm again to see if it remains
       the same.
 PASS: Change backend capabilities (replication, min_replication)
       and check if the pools have been changed.

* Tests were performed on AIO-SX/AIO-DX with k8s v1.29

Story: 2011353
Task: 51825

Depends-On: https://review.opendev.org/c/starlingx/config/+/943688

Change-Id: Id86ee8902fbc860917725741f86097c196a894fd
Signed-off-by: Erickson Silva de Oliveira <Erickson.SilvadeOliveira@windriver.com>

diff --git a/helm-charts/upstream/platform-helm/debian/deb_folder/patches/0003-ceph-csi-cephfs-add-storage-init.yaml.patch b/helm-charts/upstream/platform-helm/debian/deb_folder/patches/0003-ceph-csi-cephfs-add-storage-init.yaml.patch
--- a/helm-charts/upstream/platform-helm/debian/deb_folder/patches/0003-ceph-csi-cephfs-add-storage-init.yaml.patch
+++ b/helm-charts/upstream/platform-helm/debian/deb_folder/patches/0003-ceph-csi-cephfs-add-storage-init.yaml.patch
@@ -1,21 +1,20 @@
-From f380234343cbb6cb65ad54574099ca5adbca9cb4 Mon Sep 17 00:00:00 2001
-From: Hediberto Cavalcante da Silva <hediberto.cavalcantedasilva@windriver.com>
-Date: Thu, 4 Jan 2024 15:02:15 -0300
+From b0f74d567f5004058564f24261eed00207af023c Mon Sep 17 00:00:00 2001
+From: Erickson Silva de Oliveira <Erickson.SilvadeOliveira@windriver.com>
+Date: Thu, 27 Feb 2025 20:21:59 -0300
 Subject: [PATCH] ceph-csi-cephfs: add storage-init.yaml
 
-Signed-off-by: Hediberto Cavalcante da Silva <hediberto.cavalcantedasilva@windriver.com>
-Signed-off-by: Gabriel de Araújo Cabral <gabriel.cabral@windriver.com>
+Signed-off-by: Erickson Silva de Oliveira <Erickson.SilvadeOliveira@windriver.com>
 ---
- .../templates/storage-init.yaml               | 386 ++++++++++++++++++
- 1 file changed, 386 insertions(+)
+ .../templates/storage-init.yaml               | 396 ++++++++++++++++++
+ 1 file changed, 396 insertions(+)
  create mode 100644 charts/ceph-csi-cephfs/templates/storage-init.yaml
 
 diff --git a/charts/ceph-csi-cephfs/templates/storage-init.yaml b/charts/ceph-csi-cephfs/templates/storage-init.yaml
 new file mode 100644
-index 0000000..3ffa153
+index 0000000..9538cf5
 --- /dev/null
 +++ b/charts/ceph-csi-cephfs/templates/storage-init.yaml
-@@ -0,0 +1,386 @@
+@@ -0,0 +1,396 @@
 +{{/*
 +#
 +# Copyright (c) 2020-2024 Wind River Systems, Inc.
@@ -153,6 +152,14 @@ index 0000000..3ffa153
 +      RETURN_CODE=$?
 +      if [ ${RETURN_CODE} -ne 0 ]; then
 +        echo "Error setting the number of pool replicas (return code: ${RETURN_CODE})"
++        exit ${RETURN_CODE}
++      fi
++
++      echo "- Setting the minimum number of replicas:"
++      ceph osd pool set "${POOL}" min_size "${POOL_MIN_REPLICATION}"
++      RETURN_CODE=$?
++      if [ ${RETURN_CODE} -ne 0 ]; then
++        echo "Error setting the minimum number of pool replicas (return code: ${RETURN_CODE})"
 +        exit ${RETURN_CODE}
 +      fi
 +
@@ -385,6 +392,8 @@ index 0000000..3ffa153
 +              value: {{ $sc.chunk_size | quote }}
 +            - name: POOL_REPLICATION
 +              value: {{ $sc.replication | quote }}
++            - name: POOL_MIN_REPLICATION
++              value: {{ $sc.min_replication | quote }}
 +            - name: POOL_CRUSH_RULE_NAME
 +              value: {{ $sc.crush_rule_name | quote }}
 +            - name: CSI_DRIVER_NAME
