Update ceph-csi helm charts to v3.8.0
Update RBD/CephFS provisioners to v3.8.0 based on
https://github.com/ceph/ceph-csi/releases/tag/v3.8.0

NOTE: We use the latest versions (released until April 11, 2023)
of csi-provisioner, csi-attacher, csi-snapshotter,
csi-node-driver-register, csi-resizer, which has fewer security flaws:

https://github.com/kubernetes-csi/external-provisioner/releases/tag/v3.4.1
https://github.com/kubernetes-csi/external-attacher/releases/tag/v4.2.0
https://github.com/kubernetes-csi/external-snapshotter/releases/tag/v6.2.1
https://github.com/kubernetes-csi/node-driver-registrar/releases/tag/v2.6.3
https://github.com/kubernetes-csi/external-resizer/releases/tag/v1.7.0

Test Plan:
PASS: SX/DX/Storage app upload/apply/remove/delete/update
PASS: Create pvc using storageclass general (rbd) on SX/DX/Storage
PASS: Create pod using RBD pvc on SX/DX/Storage
PASS: Resize RBD pvc on SX/DX/Storage
PASS: Create RBD volume snapshot on SX/DX/Storage
PASS: Create pvc using storageclass cephfs on SX/DX/Storage
PASS: Create pod using cephfs pvc on SX/DX/Storage
PASS: Resize cephfs pvc on SX/DX/Storage
PASS: Create cephfs volume snapshot on SX/DX/Storage

Depends-On: https://review.opendev.org/c/starlingx/config/+/883974

Story: 2010688
Task: 47807

Signed-off-by: Erickson Silva de Oliveira <Erickson.SilvadeOliveira@windriver.com>
Change-Id: I259667de2e2149f9af2218893fadc834bff6b3a1

diff --git a/platform-helm/debian/deb_folder/patches/0003-ceph-csi-cephfs-add-storage-init.yaml.patch b/platform-helm/debian/deb_folder/patches/0003-ceph-csi-cephfs-add-storage-init.yaml.patch
--- a/platform-helm/debian/deb_folder/patches/0003-ceph-csi-cephfs-add-storage-init.yaml.patch
+++ b/platform-helm/debian/deb_folder/patches/0003-ceph-csi-cephfs-add-storage-init.yaml.patch
@@ -1,22 +1,22 @@
-From 74e705c1e18766f1e7492685c6068887c133e7a7 Mon Sep 17 00:00:00 2001
-From: Felipe Sanches Zanoni <Felipe.SanchesZanoni@windriver.com>
-Date: Mon, 10 Apr 2023 13:56:31 -0300
+From 239cfdde94db341aad0ccb15e420c4ecc3157d21 Mon Sep 17 00:00:00 2001
+From: Erickson Silva de Oliveira <Erickson.SilvadeOliveira@windriver.com>
+Date: Mon, 24 Apr 2023 16:57:46 -0300
 Subject: [PATCH] ceph-csi-cephfs: add storage-init.yaml
 
 Signed-off-by: Hediberto Cavalcante da Silva <hediberto.cavalcantedasilva@windriver.com>
 Signed-off-by: Felipe Sanches Zanoni <Felipe.SanchesZanoni@windriver.com>
-Signed-off-by: Erickson Silva <Erickson.SilvadeOliveira@windriver.com>
+Signed-off-by: Erickson Silva de Oliveira <Erickson.SilvadeOliveira@windriver.com>
 ---
- .../templates/storage-init.yaml               | 353 ++++++++++++++++++
- 1 file changed, 353 insertions(+)
+ .../templates/storage-init.yaml               | 369 ++++++++++++++++++
+ 1 file changed, 369 insertions(+)
  create mode 100644 charts/ceph-csi-cephfs/templates/storage-init.yaml
 
 diff --git a/charts/ceph-csi-cephfs/templates/storage-init.yaml b/charts/ceph-csi-cephfs/templates/storage-init.yaml
 new file mode 100644
-index 0000000..3e29fc7
+index 000000000..97052d7a9
 --- /dev/null
 +++ b/charts/ceph-csi-cephfs/templates/storage-init.yaml
-@@ -0,0 +1,353 @@
+@@ -0,0 +1,369 @@
 +{{/*
 +#
 +# Copyright (c) 2020-2023 Wind River Systems, Inc.
@@ -47,6 +47,9 @@ index 0000000..3e29fc7
 +  - apiGroups: [""]
 +    resources: ["namespaces"]
 +    verbs: ["get", "create", "list", "update"]
++  - apiGroups: ["storage.k8s.io"]
++    resources: ["csidrivers"]
++    verbs: ["get", "delete"]
 +
 +---
 +
@@ -162,6 +165,17 @@ index 0000000..3e29fc7
 +        exit ${RETURN_CODE}
 +      fi
 +    }
++
++    # Delete old driver if current fsGroupPolicy is different from "File"
++    # See: https://github.com/ceph/ceph-csi/issues/3397
++    CURRENT_FS_GROUP_POLICY=$(kubectl describe csidriver "${CSI_DRIVER_NAME}" 2>/dev/null | grep -oP 'Fs Group Policy:\K.*' | tr -d ' ')
++    if [ -n "${CURRENT_FS_GROUP_POLICY}" ] && [ "${CURRENT_FS_GROUP_POLICY}" != "File" ]; then
++       echo "Deleting old CSI driver"
++       kubectl delete csidriver "${CSI_DRIVER_NAME}"
++       if [ $? -ne 0 ]; then
++         echo "Error deleting csi driver ${CSI_DRIVER_NAME}"
++       fi
++    fi
 +
 +    # Copy from read only mount to Ceph config folder
 +    cp /tmp/ceph.conf /etc/ceph/
@@ -357,6 +371,8 @@ index 0000000..3e29fc7
 +              value: {{ $sc.replication | quote }}
 +            - name: POOL_CRUSH_RULE_NAME
 +              value: {{ $sc.crush_rule_name | quote }}
++            - name: CSI_DRIVER_NAME
++              value: {{ $.Values.driverName }}
 +          volumeMounts:
 +          - name: cephfs-storage-init-configmap-volume
 +            mountPath: /tmp
@@ -370,6 +386,5 @@ index 0000000..3e29fc7
 +      tolerations:
 +{{ toYaml . | indent 8 }}
 +{{- end}}
--- 
+--
 2.25.1
-
diff --git a/platform-helm/debian/deb_folder/patches/0008-ceph-csi-rbd-add-storage-init.yaml.patch b/platform-helm/debian/deb_folder/patches/0008-ceph-csi-rbd-add-storage-init.yaml.patch
--- a/platform-helm/debian/deb_folder/patches/0008-ceph-csi-rbd-add-storage-init.yaml.patch
+++ b/platform-helm/debian/deb_folder/patches/0008-ceph-csi-rbd-add-storage-init.yaml.patch
@@ -1,22 +1,22 @@
-From c30981ae7f7a231e0d302b552a416f7f6048b204 Mon Sep 17 00:00:00 2001
-From: Felipe Sanches Zanoni <Felipe.SanchesZanoni@windriver.com>
-Date: Mon, 10 Apr 2023 13:59:10 -0300
+From 4e3d4d76c16c4d03ba33afd0581ceac5f5ea3147 Mon Sep 17 00:00:00 2001
+From: Erickson Silva de Oliveira <Erickson.SilvadeOliveira@windriver.com>
+Date: Mon, 24 Apr 2023 17:04:02 -0300
 Subject: [PATCH] ceph-csi-rbd: add storage-init.yaml
 
 Signed-off-by: Hediberto Cavalcante da Silva <hediberto.cavalcantedasilva@windriver.com>
 Signed-off-by: Felipe Sanches Zanoni <Felipe.SanchesZanoni@windriver.com>
-Signed-off-by: Erickson Silva <Erickson.SilvadeOliveira@windriver.com>
+Signed-off-by: Erickson Silva de Oliveira <Erickson.SilvadeOliveira@windriver.com>
 ---
- .../ceph-csi-rbd/templates/storage-init.yaml  | 379 ++++++++++++++++++
- 1 file changed, 379 insertions(+)
+ .../ceph-csi-rbd/templates/storage-init.yaml  | 394 ++++++++++++++++++
+ 1 file changed, 394 insertions(+)
  create mode 100644 charts/ceph-csi-rbd/templates/storage-init.yaml
 
 diff --git a/charts/ceph-csi-rbd/templates/storage-init.yaml b/charts/ceph-csi-rbd/templates/storage-init.yaml
 new file mode 100644
-index 0000000..365b475
+index 000000000..6abd8ec3f
 --- /dev/null
 +++ b/charts/ceph-csi-rbd/templates/storage-init.yaml
-@@ -0,0 +1,379 @@
+@@ -0,0 +1,394 @@
 +{{/*
 +#
 +# Copyright (c) 2020-2023 Wind River Systems, Inc.
@@ -47,7 +47,9 @@ index 0000000..365b475
 +  - apiGroups: [""]
 +    resources: ["namespaces"]
 +    verbs: ["get", "create", "list", "update"]
-+
++  - apiGroups: ["storage.k8s.io"]
++    resources: ["csidrivers"]
++    verbs: ["get", "delete"]
 +---
 +
 +kind: ClusterRoleBinding
@@ -121,6 +123,17 @@ index 0000000..365b475
 +    #
 +    # SPDX-License-Identifier: Apache-2.0
 +    #
++
++    # Delete old driver if current fsGroupPolicy is different from "File"
++    # See: https://github.com/ceph/ceph-csi/issues/3397
++    CURRENT_FS_GROUP_POLICY=$(kubectl describe csidriver "${CSI_DRIVER_NAME}" 2>/dev/null | grep -oP 'Fs Group Policy:\K.*' | tr -d ' ')
++    if [ -n "${CURRENT_FS_GROUP_POLICY}" ] && [ "${CURRENT_FS_GROUP_POLICY}" != "File" ]; then
++       echo "Deleting old CSI driver"
++       kubectl delete csidriver "${CSI_DRIVER_NAME}"
++       if [ $? -ne 0 ]; then
++         echo "Error deleting csi driver ${CSI_DRIVER_NAME}"
++       fi
++    fi
 +
 +    # Copy from read only mount to Ceph config folder
 +    cp /tmp/ceph.conf /etc/ceph/
@@ -384,6 +397,8 @@ index 0000000..365b475
 +              value: {{ $sc.crush_rule_name | quote }}
 +            - name: POOL_CHUNK_SIZE
 +              value: {{ $sc.chunk_size | quote }}
++            - name: CSI_DRIVER_NAME
++              value: {{ $.Values.driverName }}
 +          volumeMounts:
 +            - name: rbd-storage-init-configmap-volume
 +              mountPath: /tmp
@@ -396,6 +411,5 @@ index 0000000..365b475
 +      tolerations:
 +{{ toYaml . | indent 8 }}
 +{{- end }}
--- 
+--
 2.25.1
-
